import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers/Providers";
import Navbar from "@/constants/Navigation/navbar/Navbar";
import { Noto_Sans } from 'next/font/google'
import Footer from "@/constants/Navigation/footer/Footer";

const notoSans = Noto_Sans({
  subsets: ['latin'],
  variable: '--font-noto-sans',
  weight: ['400', '800'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} antialiased`}

      >
        <Navbar />
          <Providers>
          {children}
          </Providers>
          <Footer/>

      </body>
    </html>
  );
}
