import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers/Providers";
import Navbar from "@/constants/Navigation/navbar/Navbar";
import Footer from "@/constants/Navigation/footer/Footer";
import { Roboto_Mono } from "next/font/google";

const notoSans = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-noto-sans',
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: "AirdropX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} antialiased`}

      >
        <Navbar />
        <div className="pt-[100px]">
          <Providers>
            {children}
          </Providers>
        </div>
        <Footer/>

      </body>
    </html>
  );
}
